; shaped_recipes_addon.ini
; Дополнительные рецепты для буровых труб IC2
; 6 железных пластин + 1 краник → 8 буровых труб

"ITI|I I|I I" I:OreDict:plateIron T:ic2:treetap = ic2:mining_pipe#pipe*8
"I I|ITI|I I" I:OreDict:plateIron T:ic2:treetap = ic2:mining_pipe#pipe*8
"I I|I I|ITI" I:OreDict:plateIron T:ic2:treetap = ic2:mining_pipe#pipe*8
